server:
  port: 8080
spring:
  application:
    name: location-service
  datasource:
    hikari:
      username: root
      password: password
      #数据库链接超时时间 默认为30秒
      connection-timeout: 30000
      # 空闲连接最大存活时间 默认10分钟
      idle-timeout: 600000
      # 连接默认最大生存时间 默认为30 分钟，此项目可以有效避免连接超过8小时问题
      max-lifetime: 1800000
      # 连接池最大连接数 默认为10 -->为 cpu核心数量加上
      maximum-pool-size: 5
      #此项目建议不要进行设置
      #minimum-idle: 2
      # 只读数据库
      read-only: true
      connection-test-query: select 1
  cache:
    redis:
      time-to-live: 1800000
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db_location?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  redis:
    host: localhost
    port: 6379
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${SPRING_MYSQL_HOST}:3306/db_location?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  redis:
    host: ${SPRING_REDIS_HOST}
    port: 6379
