server:
  port: 8080
spring:
  profiles:
    active: prod
  application:
    name: location-service
  datasource:
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 28000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      username: root
      password: password
  cache:
    redis:
      time-to-live: 600000
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
---
spring:
  profiles: dev
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_location?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT
---
spring:
  profiles: prod
  datasource:
    druid:
      url: jdbc:mysql://${SPRING_MYSQL_IP}:3306/db_location?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT