server:
  port: 8080
spring:
  application:
    name: location-service
  datasource:
    hikari:
      #数据库链接超时时间 默认为30秒
      connection-timeout: 30000
      # 空闲连接最大存活时间 默认10分钟
      idle-timeout: 600000
      # 连接默认最大生存时间 默认为30 分钟，此项目可以有效避免连接超过8小时问题
      max-lifetime: 1800000
      # 连接池最大连接数 默认为10 -->为 cpu核心数量加上
      maximum-pool-size: 5
      #此项目建议不要进行设置
      #minimum-idle: 2
      connection-test-query: select 1
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/db_abc
  cache:
    redis:
      time-to-live: 1800000
  redis:
    host: ${REDIS_HOST:127.0.0.1}
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.abc.location.pojo
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 25
    cache-enabled: true
---
spring:
  profiles: dev
  datasource:
    hikari:
      username: abc
      password: 123456
---
spring:
  profiles: prod
  datasource:
    hikari:
      username: abc
      password: panguicheng1993
  redis:
    password: panguicheng1993
